services:
  pyramid:
    build: ./
    image: pyramid
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ~/Mongo/pyramid:/data/db
