services:
  pyramid:
    build: ./
    image: pyramid
    ports:
      - "3001:3001"
    volumes:
      - ./index.js:/usr/src/app/index.js
      - ./src:/usr/src/app/src
      - ./vrc:/usr/src/app/vrc
    depends_on:
      - mongodb
      - redisdb
    environment:
      MONGO_URI: "mongodb://mongodb"
      REDIS_URI: "redisdb"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./.data/mongodb:/data/db

  redisdb:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./.data/redisdb:/data
